// pages/index.tsx
import Head from 'next/head';

const Home = () => {
  return (
    <div style={{ backgroundColor: 'white' }}>
      <Head>
        <title>E-Commerce Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className="container mx-auto my-8">
        <section className="flex justify-between items-center bg-gray-100 p-6 rounded-lg">
          <img src="/images/promo.png" alt="Promo" className="w-1/2" />
          <div className="w-1/2 text-center">
            <h1 className="text-4xl font-bold mb-4">Up to 10% off Voucher</h1>
            <p className="text-lg">On selected items</p>
          </div>
        </section>

        <section className="mt-8">
  <div className="flex justify-between items-center mb-4">
    <h2 className="text-2xl font-bold">Flash Sales</h2>
    <div className="flex space-x-2">
      <div className="text-center">
        <div className="text-lg font-bold">03</div>
        <div className="text-sm">Days</div>
      </div>
      <div className="text-center">
        <div className="text-lg font-bold">23</div>
        <div className="text-sm">Hours</div>
      </div>
      <div className="text-center">
        <div className="text-lg font-bold">19</div>
        <div className="text-sm">Minutes</div>
      </div>
      <div className="text-center">
        <div className="text-lg font-bold">56</div>
        <div className="text-sm">Seconds</div>
      </div>
    </div>
  </div>
  <div className="grid grid-cols-5 gap-4">
    {/* Flash Sale Items */}
    <div className="bg-white p-4 rounded-lg shadow group">
      <img src="/images/product1.png" alt="Product 1" className="w-full mb-4" />
      <div className="flex justify-between items-center mb-2">
        <h3 className="font-bold">HAVIT HV-G92 Gamepad</h3>
        <span className="text-red-500">-40%</span>
      </div>
      <div className="text-red-500">$120 <span className="line-through text-gray-500">$160</span></div>
      <div className="flex items-center mt-2">
        <span className="text-yellow-400 mr-2">★★★★★</span> <span>(88)</span>
      </div>
      <button className="bg-black text-white px-4 py-2 rounded-lg mt-2 hidden group-hover:block">Add To Cart</button>
    </div>
    <div className="bg-white p-4 rounded-lg shadow group">
      <img src="/images/product2.png" alt="Product 2" className="w-full mb-4" />
      <div className="flex justify-between items-center mb-2">
        <h3 className="font-bold">AK-900 Wired Keyboard</h3>
        <span className="text-red-500">-35%</span>
      </div>
      <div className="text-red-500">$960 <span className="line-through text-gray-500">$1160</span></div>
      <div className="flex items-center mt-2">
        <span className="text-yellow-400 mr-2">★★★★★</span> <span>(75)</span>
      </div>
      <button className="bg-black text-white px-4 py-2 rounded-lg mt-2 hidden group-hover:block">Add To Cart</button>
    </div>
    <div className="bg-white p-4 rounded-lg shadow group">
      <img src="/images/product3.png" alt="Product 3" className="w-full mb-4" />
      <div className="flex justify-between items-center mb-2">
        <h3 className="font-bold">IPS LCD Gaming Monitor</h3>
        <span className="text-red-500">-30%</span>
      </div>
      <div className="text-red-500">$370 <span className="line-through text-gray-500">$400</span></div>
      <div className="flex items-center mt-2">
        <span className="text-yellow-400 mr-2">★★★★★</span> <span>(99)</span>
      </div>
      <button className="bg-black text-white px-4 py-2 rounded-lg mt-2 hidden group-hover:block">Add To Cart</button>
    </div>
    <div className="bg-white p-4 rounded-lg shadow group">
      <img src="/images/product4.png" alt="Product 4" className="w-full mb-4" />
      <div className="flex justify-between items-center mb-2">
        <h3 className="font-bold">S-Series Comfort Chair</h3>
        <span className="text-red-500">-25%</span>
      </div>
      <div className="text-red-500">$375 <span className="line-through text-gray-500">$400</span></div>
      <div className="flex items-center mt-2">
        <span className="text-yellow-400 mr-2">★★★★★</span> <span>(99)</span>
      </div>
      <button className="bg-black text-white px-4 py-2 rounded-lg mt-2 hidden group-hover:block">Add To Cart</button>
    </div>
    <div className="bg-white p-4 rounded-lg shadow group">
      <img src="/images/product5.png" alt="Product 5" className="w-full mb-4" />
      <div className="flex justify-between items-center mb-2">
        <h3 className="font-bold">S-Series Comfort Chair</h3>
        <span className="text-red-500">-25%</span>
      </div>
      <div className="text-red-500">$375 <span className="line-through text-gray-500">$400</span></div>
      <div className="flex items-center mt-2">
        <span className="text-yellow-400 mr-2">★★★★★</span> <span>(99)</span>
      </div>
      <button className="bg-black text-white px-4 py-2 rounded-lg mt-2 hidden group-hover:block">Add To Cart</button>
    </div>
  </div>
  <div className="mt-4 text-center">
    <button className="bg-red-500 text-white px-6 py-2 rounded-lg">View All Products</button>
  </div>
</section>


<section className="mt-8">
  <h2 className="text-2xl font-bold mb-4">Browse By Category</h2>
  <div className="grid grid-cols-5 gap-4">
    <div className="flex flex-col items-center bg-white p-4 rounded-lg shadow">
      <svg xmlns="http://www.w3.org/2000/svg" className="h-12 w-12 text-blue-500" viewBox="0 0 20 20" fill="currentColor">
        <path d="M5 3a2 2 0 00-2 2v2h14V5a2 2 0 00-2-2H5zM3 9v7a2 2 0 002 2h10a2 2 0 002-2V9H3z" />
      </svg>
      <h3 className="mt-2 font-bold">Phones</h3>
    </div>
    <div className="flex flex-col items-center bg-white p-4 rounded-lg shadow">
      <svg xmlns="http://www.w3.org/2000/svg" className="h-12 w-12 text-blue-500" viewBox="0 0 20 20" fill="currentColor">
        <path d="M4 3a1 1 0 00-1 1v12a1 1 0 001 1h12a1 1 0 001-1V4a1 1 0 00-1-1H4zm3 4a1 1 0 012 0v3a1 1 0 11-2 0V7zm4 0a1 1 0 012 0v3a1 1 0 11-2 0V7z" />
      </svg>
      <h3 className="mt-2 font-bold">Computers</h3>
    </div>
    <div className="flex flex-col items-center bg-white p-4 rounded-lg shadow">
      <svg xmlns="http://www.w3.org/2000/svg" className="h-12 w-12 text-blue-500" viewBox="0 0 20 20" fill="currentColor">
        <path d="M10 2a1 1 0 00-1 1v1H7a2 2 0 00-2 2v10a2 2 0 002 2h6a2 2 0 002-2V6a2 2 0 00-2-2h-2V3a1 1 0 00-1-1zm-3 7a1 1 0 100 2h6a1 1 0 100-2H7z" />
      </svg>
      <h3 className="mt-2 font-bold">Electronics</h3>
    </div>
    <div className="flex flex-col items-center bg-white p-4 rounded-lg shadow">
      <svg xmlns="http://www.w3.org/2000/svg" className="h-12 w-12 text-blue-500" viewBox="0 0 20 20" fill="currentColor">
        <path d="M10 2a2 2 0 00-2 2v2H5a2 2 0 00-2 2v8a2 2 0 002 2h10a2 2 0 002-2v-8a2 2 0 00-2-2h-3V4a2 2 0 00-2-2z" />
      </svg>
      <h3 className="mt-2 font-bold">Home & Garden</h3>
    </div>
    <div className="flex flex-col items-center bg-white p-4 rounded-lg shadow">
      <svg xmlns="http://www.w3.org/2000/svg" className="h-12 w-12 text-blue-500" viewBox="0 0 20 20" fill="currentColor">
        <path d="M5 3a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2V5a2 2 0 00-2-2H5zm8 4a1 1 0 00-2 0v2a1 1 0 01-2 0V7a1 1 0 10-2 0v2a1 1 0 11-2 0V7a1 1 0 00-2 0v6a1 1 0 001 1h10a1 1 0 001-1V7z" />
      </svg>
      <h3 className="mt-2 font-bold">Fashion</h3>
    </div>
  </div>
</section>


        <section className="mt-8">
          <h2 className="text-2xl font-bold mb-4">Explore Our Products</h2>
          <div className="grid grid-cols-4 gap-4">
            {/* Explore Our Products */}
            <div className="bg-white p-4 rounded-lg shadow">
              <img src="/images/product9.png" alt="Product 9" className="w-full" />
              <div className="mt-2">
                <h3 className="font-bold">Product Item 1</h3>
                <p className="text-gray-700">$90.00</p>
              </div>
            </div>
            <div className="bg-white p-4 rounded-lg shadow">
              <img src="/images/product10.png" alt="Product 10" className="w-full" />
              <div className="mt-2">
                <h3 className="font-bold">Product Item 2</h3>
                <p className="text-gray-700">$100.00</p>
              </div>
            </div>
            <div className="bg-white p-4 rounded-lg shadow">
              <img src="/images/product11.png" alt="Product 11" className="w-full" />
              <div className="mt-2">
                <h3 className="font-bold">Product Item 3</h3>
                <p className="text-gray-700">$110.00</p>
              </div>
            </div>
            <div className="bg-white p-4 rounded-lg shadow">
              <img src="/images/product12.png" alt="Product 12" className="w-full" />
              <div className="mt-2">
                <h3 className="font-bold">Product Item 4</h3>
                <p className="text-gray-700">$120.00</p>
              </div>
            </div>
          </div>
        </section>

        <section className="mt-8">
          <h2 className="text-2xl font-bold mb-4">New Arrivals</h2>
          <div className="grid grid-cols-4 gap-4">
            {/* New Arrivals */}
            <div className="bg-white p-4 rounded-lg shadow">
              <img src="/images/product13.png" alt="Product 13" className="w-full" />
              <div className="mt-2">
                <h3 className="font-bold">New Arrival Item 1</h3>
                <p className="text-gray-700">$90.00</p>
              </div>
            </div>
            <div className="bg-white p-4 rounded-lg shadow">
              <img src="/images/product14.png" alt="Product 14" className="w-full" />
              <div className="mt-2">
                <h3 className="font-bold">New Arrival Item 2</h3>
                <p className="text-gray-700">$100.00</p>
              </div>
            </div>
            <div className="bg-white p-4 rounded-lg shadow">
              <img src="/images/product15.png" alt="Product 15" className="w-full" />
              <div className="mt-2">
                <h3 className="font-bold">New Arrival Item 3</h3>
                <p className="text-gray-700">$110.00</p>
              </div>
            </div>
            <div className="bg-white p-4 rounded-lg shadow">
              <img src="/images/product16.png" alt="Product 16" className="w-full" />
              <div className="mt-2">
                <h3 className="font-bold">New Arrival Item 4</h3>
                <p className="text-gray-700">$120.00</p>
              </div>
            </div>
          </div>
        </section>

        <section className="mt-8 flex justify-around items-center bg-gray-100 p-6 rounded-lg">
          <div className="flex flex-col items-center">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-12 w-12 text-green-500" viewBox="0 0 20 20" fill="currentColor">
              <path d="M10 2a1 1 0 00-1 1v1H7a2 2 0 00-2 2v10a2 2 0 002 2h6a2 2 0 002-2V6a2 2 0 00-2-2h-2V3a1 1 0 00-1-1zm-3 7a1 1 0 100 2h6a1 1 0 100-2H7z"/>
            </svg>
            <h3 className="font-bold">Free and Fast Delivery</h3>
          </div>
          <div className="flex flex-col items-center">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-12 w-12 text-green-500" viewBox="0 0 20 20" fill="currentColor">
              <path d="M9 2a7 7 0 000 14h2a7 7 0 000-14H9zM5 9a5 5 0 1110 0 5 5 0 01-10 0z"/>
            </svg>
            <h3 className="font-bold">24/7 Customer Service</h3>
          </div>
          <div className="flex flex-col items-center">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-12 w-12 text-green-500" viewBox="0 0 20 20" fill="currentColor">
              <path d="M7 9V4a1 1 0 00-2 0v5a2 2 0 11-2 0V4a3 3 0 116 0v5a2 2 0 11-2 0zm7-5a2 2 0 00-2 2v7a3 3 0 105 2.236V6a2 2 0 00-2-2zm-2 14a1 1 0 111-1 1 1 0 01-1 1zm4 0a1 1 0 111-1 1 1 0 01-1 1z"/>
            </svg>
            <h3 className="font-bold">Money Back Guarantee</h3>
          </div>
        </section>
      </main>

    </div>
  );
};

export default Home;
